[build]
  publish = "react/build"
  command = "cd react && npm install && npm run build && cd ../express && npm install && npm run build && cd .."
  functions = "express/functions"
  
[context.production]
  environment = { SERVERLESS = "1" }